# Generated by Django 4.2.7 on 2023-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='title2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='why',
            name='sub_title',
            field=models.CharField(max_length=200),
        ),
    ]
